spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_management_system
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.gym.pojo


# DeepSeek 聊天配置（用于 /api/chat/query 调用）
deepseek:
  api:
    key: "your ai api"
    url: "https://api.deepseek.com/v1/chat/completions"
  model: "deepseek-chat"


